version: '3.8'

services:
  yapplr-api:
    image: yapplr-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DATABASE_CONNECTION_STRING}
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - JwtSettings__Issuer=Yapplr.Api
      - JwtSettings__Audience=Yapplr.Client
      - JwtSettings__ExpirationInMinutes=60
      - AwsSesSettings__Region=${AWS_SES_REGION}
      - AwsSesSettings__FromEmail=${AWS_SES_FROM_EMAIL}
      - AwsSesSettings__FromName=Yapplr
      - AwsSesSettings__AccessKey=${AWS_SES_ACCESS_KEY}
      - AwsSesSettings__SecretKey=${AWS_SES_SECRET_KEY}
      - EmailProvider=AwsSes
    volumes:
      - yapplr_uploads:/app/uploads
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
    networks:
      - yapplr-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  yapplr-frontend:
    build:
      context: ../yapplr-frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=https://api.yapplr.com
    restart: unless-stopped
    networks:
      - yapplr-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - yapplr-api
      - yapplr-frontend
    restart: unless-stopped
    networks:
      - yapplr-network

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    command: certbot certonly --manual --preferred-challenges=dns --email ${CERTBOT_EMAIL} --server https://acme-v02.api.letsencrypt.org/directory --agree-tos -d *.yapplr.com -d yapplr.com

volumes:
  yapplr_uploads:

networks:
  yapplr-network:
    driver: bridge
